name: Provisioning Application

on:
  workflow_dispatch:
    inputs:
      applicationName:
        required: true
      resource_group:
        required: true
      location:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: self-hosted
    environment: dev
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_USE_OIDC: true
      TERRAFORM_STATE_FILE_NAME: "${{ inputs.applicationName }}.tfstate"
      TF_VAR_resource_group: ${{ inputs.resource_group }}
      TF_VAR_location: ${{ inputs.location }}

    steps:
    - name: 'Azure OIDC login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Remove prior state config
      run: |
        ls

    - name: Initialize Terraform
      working-directory: ./provision
      run: |
        terraform init \
          -backend-config="resource_group_name=theHerrickPerm" \
          -backend-config="storage_account_name=theherrickpermsa" \
          -backend-config="container_name=statefiles" \
          -backend-config="key=$TERRAFORM_STATE_FILE_NAME" \

    - name: Apply Terraform changes
      working-directory: ./templates
      run: terraform apply -auto-approve