name: Translation Service Provisioning

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: self-hosted
    environment: dev
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_USE_OIDC: true
      TF_VAR_resource_group: translation-service-uks-rg
      TF_VAR_storage: translationserviceukssa
      TF_VAR_appinsights: translationserviceuksai
      TF_VAR_asp: translationserviceuksasp
      TF_VAR_fa: translationserviceuksfa

    steps:
    - name: 'Azure OIDC login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize Terraform
      working-directory: ./provision
      run: |
        terraform init \
          -backend-config="resource_group_name=theHerrickPerm" \
          -backend-config="storage_account_name=theherrickpermsa" \
          -backend-config="container_name=statefiles" \
          -backend-config="key=translationService.tf" \

    - name: Apply Terraform changes
      working-directory: ./provision
      run: terraform apply -auto-approve